dows:
  role:
    items:
      - appId: aac
        name: '系统管理111'
        code: system2
      - appId: aac
        name: '用户管理233'
        code: 'user'
      - appId: aac
        name: '角色管理44'
        code: 'role'


