dows:
  cron:
    task:
      scanner:
        enable: true
        expr: 0/10 * * * * ?
        size: 1000
      sksData:
        enable: false
#        expr: 0 0/10 * * * ?
        expr: 0/10 * * * * ?
        size: 1000